name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          base: ""
          config_timezone: Asia/Seoul
          plugin_achievements: yes
#           plugin_achievements_threshold: B       # Display achievements with rank B or higher
#           plugin_achievements_secrets: yes       # Display unlocked secrets achievements
#           plugin_achievements_ignored: octonaut  # Hide octonaut achievement
#           plugin_achievements_limit: 0
